<html>
<head>
<title>d0z.me</title>
<style>
body{
font-family:monospace;
width:50%;
}
label
{
width: 4em;
float: left;
text-align: right;
margin-right: 0.5em;
display: block;
}
.submit
{
font-family:monospace;
margin-left: 4.5em;
}
</style>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-15919924-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<script>
function clear_field(el) {
if(el.defaultValue==el.value) el.value=""
}
</script>
</head>

<body>
<p>
<pre>
     __  _______                             
 .--|  ||   _   |.-----.    .--------..-----.
 |  _  ||.  |   ||-- __| __ |        ||  -__|
 |_____||.  |   ||_____||__||__|__|__||_____|
        |:  1   |                            
        |::.. . |                            
        `-------'                            

</pre>
by Ben Schmidt (supernothing) of <a target="_blank" href="http://spareclockcycles.org">spareclockcycles.org</a>
</p>
