<p>
<form method="POST" action="">
<label>Link: </label><input onfocus="clear_field(this)" type="text" size="100" name="link" value="http://www.example.com"/><br/>
<label>Target: </label><input onfocus="clear_field(this)" type="text" size="100" name="target" value="http://www.example.com"/><br/>
<label>Title: </label><input type="text" size="100" name="title"/><br/>
<label>Method: </label><input type="radio" name="method" value="POST" checked>POST <input type="radio" name="method" value="GET"> GET
<br/>
<input class="submit" type="submit" name="submit" value="Get my link!"/>
</p>
